Repository goerli/parity-goerli, pull requests merged in 2019-01, with the labels that each got.

#29 Add Sealing
  ethcore/src/block.rs
  ethcore/src/engines/clique/mod.rs
  ethcore/src/engines/clique/signer_snapshot.rs
  ethcore/src/engines/clique/step_service.rs
  ethcore/src/engines/mod.rs
Labels: A4-gotissues 💥, M4-core ⛓

#40 convert spaces to tabs
  .travis.yml
  ethcore/src/block.rs
  ethcore/src/engines/clique/mod.rs
  ethcore/src/engines/clique/params.rs
  ethcore/src/engines/clique/signer_snapshot.rs
  ethcore/src/engines/clique/step_service.rs
  ethcore/src/engines/mod.rs
  json/src/spec/clique.rs
Labels: A2-insubstantial 👶

#49 ethcore: prepare for the real goerli to launch
  ethcore/res/ethereum/goerli.json
Labels: A0-pleasereview 🤓, M2-config 📂
